name: Saludo

on: 
    push:
        branches: [develop]

    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Saludo
              run: echo "Hola mundo"